project:
  type: website

website:
  title: "Dashboards"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: example_1.qmd
        text: 'Example #1'
      - href: example_2.qmd
        text: 'Example #2'
      - href: example_3.qmd
        text: 'Example #3'
      - href: example_4.qmd
        text: 'Example #4'
format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

